# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

name: MUSEO ARTE Y CIUDAD
title: Museo Arte y Ciudad
email: fernanz@me.com
author: Fernando Mayorga G.
exclude: [main.scss, config.rb, crono-faal.html, bicentenario.html, guayaquil-ebook.html]
description: >- # this means to ignore newlines until "baseurl:"
  Este sitio ha sido creado por FERNANDO MAYORGA para informar sobre las actividades y eventos culturales de la Dirección de Cultura del Municipio de guayaquil. MMDG ©2020
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://museoarteyciudad.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: pretty
twitter_username: fernanz
github_username:  fernanz

collections:
  arts:
    output: true
  people:
    output: true
  capsulas:
    output: true
  destacadas:
    output: true

defaults:
  - scope:
      type: arts
    values:
      layout: ars
  - scope:
      type: people
    values:
      layout: person
  - scope:
      type: capsulas
    values:
      layout: capsule

# Build settings
# plugins:
#  - jekyll-feed
